Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# load data
data = az.load_arviz_data('regression1d')
X = data.observed_data.y_dim_0.values
Y = data.observed_data.y.values
y_pp = data.posterior_predictive.y.values
# plot
f1 = figure(plot_width=600, plot_height=600, toolbar_location="below")
az.plot_hdi(X, y_pp, color="#b5a7b6", show=False, ax=f1)
f1.scatter(X, Y, marker="circle", fill_color="#0d7591")

show(f1)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[5], line 7[0m
[1;32m      5[0m y_pp [38;5;241m=[39m data[38;5;241m.[39mposterior_predictive[38;5;241m.[39my[38;5;241m.[39mvalues
[1;32m      6[0m [38;5;66;03m# plot[39;00m
[0;32m----> 7[0m f1 [38;5;241m=[39m [43mfigure[49m[43m([49m[43mplot_width[49m[38;5;241;43m=[39;49m[38;5;241;43m600[39;49m[43m,[49m[43m [49m[43mplot_height[49m[38;5;241;43m=[39;49m[38;5;241;43m600[39;49m[43m,[49m[43m [49m[43mtoolbar_location[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mbelow[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      8[0m az[38;5;241m.[39mplot_hdi(X, y_pp, color[38;5;241m=[39m[38;5;124m"[39m[38;5;124m#b5a7b6[39m[38;5;124m"[39m, show[38;5;241m=[39m[38;5;28;01mFalse[39;00m, ax[38;5;241m=[39mf1)
[1;32m      9[0m f1[38;5;241m.[39mscatter(X, Y, marker[38;5;241m=[39m[38;5;124m"[39m[38;5;124mcircle[39m[38;5;124m"[39m, fill_color[38;5;241m=[39m[38;5;124m"[39m[38;5;124m#0d7591[39m[38;5;124m"[39m)

File [0;32m/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/bokeh/plotting/_figure.py:190[0m, in [0;36mfigure.__init__[0;34m(self, *arg, **kw)[0m
[1;32m    188[0m [38;5;28;01mfor[39;00m name [38;5;129;01min[39;00m kw[38;5;241m.[39mkeys():
[1;32m    189[0m     [38;5;28;01mif[39;00m name [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m names:
[0;32m--> 190[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_attribute_error_with_matches[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mnames[49m[43m [49m[38;5;241;43m|[39;49m[43m [49m[43mopts[49m[38;5;241;43m.[39;49m[43mproperties[49m[43m([49m[43m)[49m[43m)[49m
[1;32m    192[0m [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m([38;5;241m*[39marg, [38;5;241m*[39m[38;5;241m*[39mkw)
[1;32m    194[0m [38;5;28mself[39m[38;5;241m.[39mx_range [38;5;241m=[39m get_range(opts[38;5;241m.[39mx_range)

File [0;32m/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/bokeh/core/has_props.py:368[0m, in [0;36mHasProps._raise_attribute_error_with_matches[0;34m(self, name, properties)[0m
[1;32m    365[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m matches:
[1;32m    366[0m     matches, text [38;5;241m=[39m [38;5;28msorted[39m(properties), [38;5;124m"[39m[38;5;124mpossible[39m[38;5;124m"[39m
[0;32m--> 368[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124munexpected attribute [39m[38;5;132;01m{[39;00mname[38;5;132;01m!r}[39;00m[38;5;124m to [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m, [39m[38;5;132;01m{[39;00mtext[38;5;132;01m}[39;00m[38;5;124m attributes are [39m[38;5;132;01m{[39;00mnice_join(matches)[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mAttributeError[0m: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width
AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width

